# Configuration file for the Sphinx documentation builder.
#
# This file only contains a selection of the most common options. For a full
# list see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# Configuration file for the Sphinx documentation builder.
#
# This file only contains a selection of the most common options. For a full
# list see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
# import os
# import sys
# sys.path.insert(0, os.path.abspath('.'))
from datetime import date


# -- Read the Docs Sphinx Theme ----------------------------------------------
import sphinx_rtd_theme


# -- Project information -----------------------------------------------------

# The documented project’s name.
project = 'MFR'

# The author name(s) of the document. The default value is 'unknown'.
author = 'CTB Automatisierungstechnik GmbH'

# A copyright statement in the style '2008, Author Name'.
copyright = f"{date.today().year}, CTB Automatisierungstechnik GmbH"

# The major project version, used as the replacement for |version|.
# For example, for the Python documentation, this may be something like 2.6.
version = '1.0'

# The full project version, used as the replacement for |release| and e.g. 
# in the HTML templates. For example, for the Python documentation, 
# this may be something like 2.6.0rc1.
release = '1.0.0'
# If you don’t need the separation provided between version and release, 
# just set them both to the same value.


# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom ones.
extensions = [
    'rinoh.frontend.sphinx',
    'sphinx.ext.todo',
    'sphinx.ext.mathjax',
    'myst_parser',
    'sphinx_design',
    'sphinxext.opengraph',
    'sphinxcontrib.mermaid',
    'sphinxcontrib.swaggerui'
]

# The file extensions of source files. Sphinx considers the files with this 
# suffix as sources. The value can be a dictionary mapping file extensions to
# file types. By default, Sphinx only supports 'restructuredtext' file type.
source_suffix = {
    '.rst': 'restructuredtext',
    '.txt': 'markdown',
    '.md': 'markdown',
}

# The encoding of all reST source files. The recommended encoding, and the 
# default value, is 'utf-8-sig'.
#source_encoding = 'utf-8-sig'

# If given, a dictionary of parser classes for different source suffices. 
# The keys are the suffix, the values can be either a class or a string giving 
# a fully-qualified name of a parser class. The parser class can be either 
# docutils.parsers.Parser or sphinx.parsers.Parser. Files with a suffix that is
# not in the dictionary will be parsed with the default reStructuredText parser.
#source_parsers = {'.md': 'recommonmark.parser.CommonMarkParser'}

# The document name of the “root” document, that is, the document that 
# contains the root toctree directive. Default is 'index'.
root_doc = 'index'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = ['_build', 'Thumbs.db',
                    '.DS_Store', '.vscode', '.devcontainer', 'README.md']

# A list of glob-style patterns [1] that are used to find source files. 
# They are matched against the source file names relative to the source 
# directory, using slashes as directory separators on all platforms. 
# The default is **, meaning that all files are recursively included from the 
# source directory. exclude_patterns has priority over include_patterns.
# include_patterns = ['']

# A list of paths that contain extra templates (or templates that overwrite 
# builtin/theme-specific templates). 
# Relative paths are taken as relative to the configuration directory.
templates_path = ['_templates']


# -- Options for internationalization ----------------------------------------

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'de'


# -- Options for markdown ----------------------------------------------------

# markdown
myst_html_meta = {
    "description lang=en": "metadata description",
    "description lang=es": "descripcion de metadata",
    "keywords": "Sphinx, MyST",
    "property=og:locale":  "es_AR"
}


# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages. See the documentation for
# a list of builtin themes. The default is 'alabaster'.
#html_theme = 'alabaster'

# Theme options are theme-specific and customize the look and feel of a 
# theme further.
# For a list of options available for each theme, see the documentation.
# html_theme_options = {}

# A list of paths that contain custom themes, either as subdirectories or 
# as zip files.
# Relative paths are taken as relative to the configuration directory.
#html_theme_path = []

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

#html_style = 
#html_title = 
#html_short_title = 
#html_baseurl = 

#html_theme = 'default'
#html_theme = 'classic'
#html_theme = 'basicstrap'

# -- HTML them sphinx_rtd_theme ----------------------------------------------

#html_theme = 'sphinx_rtd_theme'
#html_theme_path = [sphinx_rtd_theme.get_html_theme_path()]

# -- HTML them sphinx_book_theme ---------------------------------------------

html_theme = "sphinx_book_theme"
html_theme_path = ["_themes", ]
#html_logo = "_static/logo-wide.svg"
html_logo = "_static/ctb-logo.png"
html_favicon = "_static/logo-square.svg"
html_title = "MFR Dokumentation"
html_theme_options = {
    "home_page_in_toc": True,
    "github_url": "https://github.com/ctbautomation/mfresp32-doc-user",
    "repository_url": "https://github.com/ctbautomation/mfresp32-doc-user",
    "repository_branch": "main",
    "path_to_docs": "/",
    "use_repository_button": True,
    "use_edit_page_button": True,
}


# -- Options for LaTeX output ------------------------------------------------

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    'papersize': 'a4paper',

    # The font size ('10pt', '11pt' or '12pt').
    #'pointsize': '10pt',

    # Additional stuff for the LaTeX preamble.
    'preamble': '\setcounter{tocdepth}{2}',

    # Latex figure (float) alignment
    # 'figure_align': 'htbp',

    'babel' : '\\usepackage[ngerman]{babel}',
	
    'extraclassoptions': ',openany,oneside'
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
    (root_doc, 'MFR.tex', 'MFR documentation',
     'CTB Automatisierungstechnik GmbH', 'manual'),
]

latex_show_pagerefs = True
latex_use_xindy = True

# The name of an image file (relative to this directory) to place at the top of
# the title page.
latex_logo = '_static/ctb-logo.png'

# If true, show page references after internal links.
# latex_show_pagerefs = False

# If true, show URL addresses after external links.
# latex_show_urls = False

# Documents to append as an appendix to all manuals.
# latex_appendices = []

# If false, no module index is generated.
# latex_domain_indices = True


# -- Extension configuration -------------------------------------------------


# -- Options for intersphinx extension ---------------------------------------


# -- Options for todo extension ----------------------------------------------
# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = True


# -- Options for rinohtype extension -----------------------------------------
# configuration for rinohtype extension.
# https://www.mos6581.org/rinohtype/master/sphinx.html?highlight=rinoh_logo#confval-rinoh_documents
rinoh_documents = [dict(doc='index',      # top-level file (index.rst)
                        target='MFR')]   # output file (project.pdf)